version: '3'
services:
  app:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - '5050:5050'
    environment:
      PORT: '5050'
      ML_API_HOST: http://34.101.114.31:8080
      DB_URL: postgres://postgres:postgres@pg:5432/postgres?sslmode=disable
    volumes:
      - '.:/app'
    depends_on:
      pg:
        condition: service_healthy

  pg:
    image: postgres:alpine
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres